version: '3'
services:

  app:
    restart: always
    container_name: app
    build:
      dockerfile: Dockerfile.app
      context: .
    environment:
      DB: mongodb://mongo:27017/${DB_NAME}?w=1
      COL_NAME:
    depends_on:
      - mongo
    ports:
      - 8000:8000

  mongo:
    restart: always
    container_name: mongo
    build:
      dockerfile: Dockerfile.db
      context: .
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./db:/data/db:rw
    ports:
      - 27017:27017
