version: '3'
services:

  app:
    build:
      dockerfile: Dockerfile.app
      context: .
    environment:
      DB: mongodb://mongo:27017/spark?w=1
    depends_on:
      - mongo
    ports:
      - 8000:8000

  mongo:
    restart: always
    build:
      dockerfile: Dockerfile.db
      context: .
    environment:
      MONGO_INITDB_DATABASE: spark
    volumes:
      - ./db:/data/db:rw
    ports:
      - 27017:27017
