version: '3'
services:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env-node
#    environment:
#      DB: mongodb://mongo:27017/trlogs?w=1
#    depends_on:
#      # i need make sure mongo is ready to accept connections before starting node. healthcheck?
#      - mongo

  mongo:
    restart: always
    build:
      dockerfile: Dockerfile.db
      context: .
    environment:
      MONGO_INITDB_DATABASE: spark
    volumes:
      - ./db:/data/db:rw
    ports:
      - 27017:27017
